// Page context and composition relationships for all 61 components
// Used by generate_skills.js to add "When to Use" and "Composes With" sections

const PAGE_CONTEXT = {
    'accordion': { pages: ['FAQ page', 'Settings panel', 'Documentation', 'Product details'], composesWith: ['cards', 'forms', 'inputs', 'icons'] },
    'ai-chat': { pages: ['Chat application', 'Support widget', 'Dashboard assistant'], composesWith: ['inputs', 'buttons', 'avatars', 'scroll-areas', 'spinner-loaders'] },
    'alert': { pages: ['Dashboard', 'Form validation', 'System status', 'Settings'], composesWith: ['buttons', 'icons', 'toasts'] },
    'announcement': { pages: ['Landing page top bar', 'Product launch', 'App update notice'], composesWith: ['buttons', 'badges', 'links'] },
    'avatar': { pages: ['Navigation bar', 'Chat messages', 'Team page', 'Comments', 'Profile'], composesWith: ['badges', 'tooltips', 'dropdowns', 'cards'] },
    'background': { pages: ['Hero section', 'Full-page backdrop', 'Section divider', 'Auth pages'], composesWith: ['heroes', 'cards', 'calls-to-action'] },
    'badge': { pages: ['Navigation items', 'Table cells', 'Card headers', 'Avatar overlays'], composesWith: ['avatars', 'buttons', 'cards', 'navigation-menus'] },
    'border': { pages: ['Card highlights', 'Input focus states', 'Section dividers', 'Image frames'], composesWith: ['cards', 'inputs', 'images', 'buttons'] },
    'button': { pages: ['Every page — forms, CTAs, navigation, toolbars, dialogs'], composesWith: ['forms', 'heroes', 'cards', 'dialogs', 'navigation-menus', 'tooltips'] },
    'calendar': { pages: ['Scheduling app', 'Dashboard', 'Date picker dropdown', 'Booking flow'], composesWith: ['date-pickers', 'popovers', 'cards', 'forms'] },
    'call-to-action': { pages: ['Landing page final section', 'Blog post footer', 'Pricing page bottom', 'Email signup'], composesWith: ['buttons', 'inputs', 'backgrounds', 'badges'] },
    'card': { pages: ['Dashboard stats', 'Feature grid', 'Blog listing', 'Product catalog', 'Portfolio'], composesWith: ['buttons', 'badges', 'images', 'avatars', 'icons'] },
    'carousel': { pages: ['Product gallery', 'Testimonial slider', 'Portfolio showcase', 'Onboarding'], composesWith: ['cards', 'images', 'testimonials', 'buttons', 'paginations'] },
    'checkbox': { pages: ['Forms', 'Settings', 'Todo lists', 'Filter panels', 'Table row selection'], composesWith: ['forms', 'labels', 'cards'] },
    'client': { pages: ['Landing page social proof', 'About page', 'Case studies header'], composesWith: ['heroes', 'testimonials', 'calls-to-action'] },
    'comparison': { pages: ['Pricing page', 'Product comparison', 'Feature matrix'], composesWith: ['tables', 'cards', 'badges', 'buttons', 'tabs'] },
    'date-picker': { pages: ['Forms', 'Scheduling', 'Dashboard filters', 'Booking'], composesWith: ['calendars', 'popovers', 'inputs', 'forms'] },
    'dialog': { pages: ['Confirmation flows', 'Detail views', 'Forms', 'Image lightbox', 'Settings'], composesWith: ['forms', 'buttons', 'inputs', 'cards'] },
    'dock': { pages: ['Desktop-style apps', 'Creative tools', 'Media players'], composesWith: ['tooltips', 'icons', 'buttons'] },
    'dropdown': { pages: ['Navigation', 'Settings', 'Context menus', 'Filters'], composesWith: ['buttons', 'navigation-menus', 'icons', 'badges'] },
    'empty-state': { pages: ['Dashboard with no data', 'Search with no results', 'First-time user views'], composesWith: ['buttons', 'images', 'icons'] },
    'feature': { pages: ['Landing page features section', 'Product tour', 'About page'], composesWith: ['cards', 'icons', 'images', 'badges', 'buttons'] },
    'file-tree': { pages: ['Code editor', 'File manager', 'Documentation sidebar'], composesWith: ['icons', 'scroll-areas', 'sidebars'] },
    'file-upload': { pages: ['Forms', 'Profile settings', 'Content management', 'Chat attachments'], composesWith: ['buttons', 'spinner-loaders', 'toasts', 'forms'] },
    'footer': { pages: ['Every page bottom — landing, dashboard, blog, docs'], composesWith: ['links', 'icons', 'inputs', 'buttons'] },
    'form': { pages: ['Auth pages', 'Settings', 'Contact page', 'Checkout', 'Onboarding'], composesWith: ['inputs', 'buttons', 'checkboxes', 'selects', 'radio-groups', 'text-areas'] },
    'hero': { pages: ['Landing page first fold', 'Product homepage', 'Portfolio entry', 'App marketing'], composesWith: ['buttons', 'backgrounds', 'badges', 'clients', 'images'] },
    'hook': { pages: ['Any page — utility hooks for animations, scroll, resize, media queries'], composesWith: ['all components'] },
    'icon': { pages: ['Every page — buttons, navigation, cards, badges, inputs'], composesWith: ['buttons', 'navigation-menus', 'cards', 'badges', 'inputs'] },
    'image': { pages: ['Portfolio', 'Product gallery', 'Blog post', 'About page', 'Hero section'], composesWith: ['cards', 'carousels', 'heroes', 'dialogs'] },
    'input': { pages: ['Forms', 'Search bars', 'Chat input', 'Settings', 'Auth pages'], composesWith: ['forms', 'buttons', 'icons', 'labels', 'popovers'] },
    'link': { pages: ['Navigation', 'Footer', 'Breadcrumbs', 'Inline text', 'Cards'], composesWith: ['navigation-menus', 'footers', 'cards', 'icons'] },
    'map': { pages: ['Contact page', 'Store locator', 'Real estate listing', 'Travel app'], composesWith: ['cards', 'popovers', 'buttons'] },
    'menu': { pages: ['Context menus', 'Right-click menus', 'Action menus', 'Navigation'], composesWith: ['buttons', 'icons', 'dropdowns', 'navigation-menus'] },
    'navigation-menu': { pages: ['Site header on every page', 'Mobile nav drawer', 'App top bar'], composesWith: ['buttons', 'avatars', 'badges', 'dropdowns', 'icons', 'links'] },
    'notification': { pages: ['Dashboard real-time updates', 'Social feed', 'Messaging app'], composesWith: ['avatars', 'badges', 'buttons', 'toasts', 'scroll-areas'] },
    'number': { pages: ['Dashboard KPIs', 'Pricing display', 'Statistics section', 'Counters'], composesWith: ['cards', 'badges', 'icons'] },
    'pagination': { pages: ['Blog listing', 'Table data', 'Search results', 'Product catalog'], composesWith: ['tables', 'cards', 'buttons'] },
    'popover': { pages: ['Hover previews', 'Quick actions', 'Rich tooltips', 'Settings'], composesWith: ['buttons', 'avatars', 'cards', 'forms'] },
    'pricing-section': { pages: ['Landing page pricing', 'Pricing page', 'Upgrade modal'], composesWith: ['cards', 'buttons', 'badges', 'toggles', 'comparisons', 'tabs'] },
    'radio-group': { pages: ['Forms', 'Settings', 'Preference selection', 'Pricing toggle'], composesWith: ['forms', 'cards', 'labels'] },
    'scroll-area': { pages: ['Sidebars', 'Chat panels', 'Code previews', 'Long content sections'], composesWith: ['sidebars', 'ai-chats', 'tables', 'cards'] },
    'select': { pages: ['Forms', 'Filters', 'Settings', 'Data tables', 'Navigation'], composesWith: ['forms', 'inputs', 'buttons', 'popovers'] },
    'shader': { pages: ['Hero backgrounds', 'Loading screens', 'About page ambience', 'Auth page bg'], composesWith: ['heroes', 'backgrounds', 'calls-to-action'] },
    'sidebar': { pages: ['Dashboard navigation', 'Settings panel', 'Documentation', 'Admin'], composesWith: ['navigation-menus', 'icons', 'avatars', 'badges', 'scroll-areas'] },
    'sign-in': { pages: ['Login page', 'Auth modal', 'Protected route gate'], composesWith: ['forms', 'inputs', 'buttons', 'links', 'icons'] },
    'sign-up': { pages: ['Registration page', 'Onboarding first step', 'Auth modal'], composesWith: ['forms', 'inputs', 'buttons', 'checkboxes', 'links'] },
    'slider': { pages: ['Settings', 'Image editors', 'Product configurator', 'Audio/video player'], composesWith: ['forms', 'inputs', 'labels', 'tooltips'] },
    'spinner-loader': { pages: ['Loading states everywhere', 'Button loading', 'Page transitions', 'Data fetching'], composesWith: ['buttons', 'cards', 'tables', 'forms'] },
    'table': { pages: ['Dashboard data views', 'Admin panels', 'Pricing comparison', 'Reports'], composesWith: ['paginations', 'buttons', 'badges', 'checkboxes', 'dropdowns', 'scroll-areas'] },
    'tab': { pages: ['Settings panels', 'Product details', 'Dashboard sections', 'Code examples'], composesWith: ['cards', 'forms', 'tables', 'scroll-areas'] },
    'tag': { pages: ['Blog post metadata', 'Product filters', 'Skill labels', 'Search tokens'], composesWith: ['cards', 'inputs', 'badges'] },
    'testimonial': { pages: ['Landing page social proof', 'About page', 'Case study'], composesWith: ['avatars', 'cards', 'carousels', 'clients'] },
    'text': { pages: ['Hero headlines', 'Blog content', 'Feature descriptions', 'Marketing copy'], composesWith: ['heroes', 'cards', 'features'] },
    'text-area': { pages: ['Forms', 'Comment sections', 'Chat input', 'Feedback forms', 'Note editors'], composesWith: ['forms', 'buttons', 'labels'] },
    'toast': { pages: ['Form submission feedback', 'Action confirmations', 'Error notifications'], composesWith: ['buttons', 'icons', 'alerts'] },
    'toggle': { pages: ['Settings', 'Dark mode switch', 'Feature flags', 'Notification preferences'], composesWith: ['forms', 'cards', 'labels'] },
    'tooltip': { pages: ['Icon buttons', 'Truncated text', 'Chart data points', 'Action hints'], composesWith: ['buttons', 'icons', 'avatars', 'badges'] },
    'video': { pages: ['Hero backgrounds', 'Product demos', 'Testimonials', 'About page'], composesWith: ['heroes', 'cards', 'dialogs', 'buttons'] },
};

// Fallback techniques for components with 0 training prompts
const FALLBACK_TECHNIQUES = {
    'card': ['Framer Motion animations', 'Framer Motion spring physics', 'Framer Motion useMotionValue', 'Framer Motion useTransform', 'Glassmorphism / backdrop blur', 'CSS gradients', 'CSS keyframe animations', 'React.forwardRef pattern', 'cn() utility (clsx + tailwind-merge)', 'CVA (class-variance-authority) variants', 'Radix UI primitives', 'Lucide React icons', 'React refs', 'React state management', 'ARIA accessibility attributes'],
    'dialog': ['Framer Motion animations', 'AnimatePresence exit animations', 'Glassmorphism / backdrop blur', 'Radix UI primitives', 'React.forwardRef pattern', 'cn() utility (clsx + tailwind-merge)', 'CSS keyframe animations', 'React refs', 'React state management', 'ARIA accessibility attributes', 'Lucide React icons'],
    'sign-up': ['Framer Motion animations', 'React Hook Form', 'Zod schema validation', 'cn() utility (clsx + tailwind-merge)', 'Radix UI primitives', 'Lucide React icons', 'React state management', 'CSS gradients', 'Next.js Link routing', 'ARIA accessibility attributes'],
    'file-upload': ['Framer Motion animations', 'React state management', 'React refs', 'Drag and drop', 'cn() utility (clsx + tailwind-merge)', 'Lucide React icons', 'CSS keyframe animations', 'ARIA accessibility attributes'],
    'tab': ['Framer Motion animations', 'Framer Motion spring physics', 'Radix UI primitives', 'cn() utility (clsx + tailwind-merge)', 'CVA (class-variance-authority) variants', 'AnimatePresence exit animations', 'React state management', 'CSS keyframe animations', 'ARIA accessibility attributes', 'Lucide React icons'],
    'tag': ['Framer Motion animations', 'cn() utility (clsx + tailwind-merge)', 'CVA (class-variance-authority) variants', 'Lucide React icons', 'React state management', 'CSS gradients', 'ARIA accessibility attributes'],
    'text': ['Framer Motion animations', 'CSS gradients', 'CSS keyframe animations', 'cn() utility (clsx + tailwind-merge)', 'React state management', 'Intersection Observer / useInView'],
    'text-area': ['Framer Motion animations', 'React Hook Form', 'React refs', 'cn() utility (clsx + tailwind-merge)', 'Radix UI primitives', 'React state management', 'ARIA accessibility attributes'],
    'toggle': ['Framer Motion animations', 'Framer Motion spring physics', 'Radix UI primitives', 'cn() utility (clsx + tailwind-merge)', 'React state management', 'CSS keyframe animations', 'ARIA accessibility attributes'],
    'tooltip': ['Framer Motion animations', 'AnimatePresence exit animations', 'Radix UI primitives', 'cn() utility (clsx + tailwind-merge)', 'React state management', 'CSS gradients', 'Glassmorphism / backdrop blur'],
    'announcement': ['Framer Motion animations', 'AnimatePresence exit animations', 'cn() utility (clsx + tailwind-merge)', 'CSS gradients', 'CSS keyframe animations', 'Lucide React icons', 'React state management', 'Next.js Link routing'],
    'background': ['CSS gradients', 'CSS keyframe animations', 'Three.js / React Three Fiber', 'GLSL shaders', 'HTML Canvas rendering', 'React refs', 'React state management', 'Framer Motion animations'],
    'map': ['React refs', 'React state management', 'React effects', 'CSS gradients', 'Framer Motion animations', 'Intersection Observer API'],
};

// Fallback dependencies for components with 0 training prompts
const FALLBACK_DEPS = {
    'card': ['class-variance-authority', 'clsx', 'tailwind-merge', 'framer-motion', 'lucide-react', '@radix-ui/react-slot'],
    'dialog': ['@radix-ui/react-dialog', 'framer-motion', 'class-variance-authority', 'clsx', 'tailwind-merge', 'lucide-react'],
    'sign-up': ['framer-motion', 'react-hook-form', '@hookform/resolvers', 'zod', 'clsx', 'tailwind-merge', 'lucide-react', '@radix-ui/react-label'],
    'file-upload': ['framer-motion', 'clsx', 'tailwind-merge', 'lucide-react', 'react-dropzone'],
    'tab': ['@radix-ui/react-tabs', 'framer-motion', 'class-variance-authority', 'clsx', 'tailwind-merge', 'lucide-react'],
    'tag': ['class-variance-authority', 'clsx', 'tailwind-merge', 'framer-motion', 'lucide-react'],
    'text': ['framer-motion', 'clsx', 'tailwind-merge', 'class-variance-authority'],
    'text-area': ['@radix-ui/react-label', 'framer-motion', 'clsx', 'tailwind-merge', 'react-hook-form'],
    'toggle': ['@radix-ui/react-switch', 'framer-motion', 'clsx', 'tailwind-merge', 'class-variance-authority'],
    'tooltip': ['@radix-ui/react-tooltip', 'framer-motion', 'clsx', 'tailwind-merge'],
    'announcement': ['framer-motion', 'clsx', 'tailwind-merge', 'lucide-react'],
    'background': ['framer-motion', 'three', '@react-three/fiber', '@react-three/drei', 'clsx', 'tailwind-merge'],
    'map': ['framer-motion', 'clsx', 'tailwind-merge', 'lucide-react'],
};

module.exports = { PAGE_CONTEXT, FALLBACK_TECHNIQUES, FALLBACK_DEPS };
