// ─── Generative DNA Part 3: date-picker through form ───
const DNA_3 = {
    'date-picker': {
        layout: ["Single date input with calendar dropdown", "Date range dual input", "Inline always-visible calendar", "Week picker strip", "Month/year only selector"],
        surface: ["Glass dropdown on dark background", "Outlined calendar with brand-color selected", "Minimal flat with hover highlights", "Card-elevated with shadow", "Frosted pill input with glass dropdown"],
        motion: ["Dropdown springs in with scale from input", "Date selection pops with micro-bounce", "Month transition slides left/right", "Input text morphs to formatted date", "Calendar cells stagger-in by row"],
        mood: ["Dashboard — compact, data-focused", "Booking — range-centric, date highlighting", "Minimal — iOS-style wheel/picker feel", "Enterprise — ISO format, week numbers visible", "Playful — emoji for special dates, colorful"],
        composition: ["Form field date input", "Filter bar date range", "Booking date selector", "Event creation dialog", "Dashboard date filter"],
        spawnRecipes: [
            "Glass Date — frosted-glass input pill. Click opens glass dropdown calendar with backdrop-blur-xl. Selected date has brand-color ring + glow. Month arrows spring animate. Calendar springs in from input anchor point with scale. Today has pulsing dot.",
            "Range Sweep — dual date input for start/end. Calendar shows range with gradient fill between dates. Dragging either end updates in real-time. Range dates glow subtly. Input displays formatted 'Jan 12 - Jan 18'.",
            "Inline Planner — always-visible calendar embedded in a card. Selected date highlights with brand fill + lift. Events shown as colored dots below date numbers. Navigate months via swipe gesture or arrows with slide transition.",
            "Wheel Selector — iOS-style scrolling drum picker for day/month/year in three columns. Snap scroll physics. Selected row centered and enlarged. Backdrop fades above and below center. Haptic-style visual feedback.",
        ],
    },
    'dialog': {
        layout: ["Centered modal with backdrop", "Full-screen takeover", "Slide-in side panel (drawer)", "Bottom sheet (mobile-first)", "Nested multi-step wizard modal"],
        surface: ["Frosted glass panel on blurred backdrop", "Solid dark card with brand-color header bar", "Outlined container with shadow", "Full-bleed content with no chrome", "Split dialog (sidebar nav + content area)"],
        motion: ["Scale-in from center with spring (0.95 → 1.0)", "Backdrop fades in while modal slides up", "Exit via scale-down + opacity + backdrop fade", "Drawer slides from right with spring", "Content crossfade between wizard steps"],
        mood: ["Confirmation — warning icon, two-button footer", "Form dialog — input fields, stepped sections", "Media viewer — full-screen, dark, content-focused", "Alert — urgent, icon prominent, single action", "Premium — glass card, minimal lines, luxe feel"],
        composition: ["Confirmation before destructive action", "Settings/preferences editor", "Image/video lightbox viewer", "Complex form multi-step", "Notification detail expansion"],
        spawnRecipes: [
            "Glass Command — centered frosted-glass modal with backdrop-blur-2xl dimmed backdrop (black/60). Modal springs in from scale-0.95. Header with title + close X. Content area. Two-button footer. Close button has hover glow. Escape key dismisses.",
            "Drawer Sheet — slides in from right edge. 400px wide. Dark background with brand-color top accent line. Close button + title header. Scrollable content area. Exit via slide-right + backdrop fade. Can be swiped closed on mobile.",
            "Bottom Sheet — mobile-first sheet rising from bottom. Drag handle bar at top. Snap points at 50% and 90% viewport height. Draggable via touch. Spring physics on release. Backdrop dims proportionally to sheet position.",
            "Wizard Flow — multi-step modal with progress indicator at top (step dots or bar). Content area crossfades between steps. Back/Next buttons. Step transitions slide left-to-right. Final step has celebration animation.",
        ],
    },
    'dock': {
        layout: ["Bottom-center horizontal dock", "Side rail vertical dock", "Floating pill dock", "Auto-hide dock (slide-out on hover edge)", "Corner cluster dock"],
        surface: ["Frosted glass bar with border-white/10", "Solid dark panel with inner glow", "Individual glass icon containers", "Outlined capsule shape", "Gradient mesh background dock"],
        motion: ["macOS-style magnification on hover proximity", "Icon pop-up spring on hover", "Dock auto-shows on mouse near edge", "Active icon bounce animation", "Tooltip floats above on hover delay"],
        mood: ["macOS — magnification, reflections, glass", "Minimal — thin bar, no magnification, clean", "Gaming — neon icons, pulse on notification", "Productivity — grouped sections with dividers", "Creative — irregular spacing, playful bounce"],
        composition: ["Application launcher bar", "Quick action toolbar", "Navigation primary rail", "Media player controls bar", "Chat app quick-switch panel"],
        spawnRecipes: [
            "macOS Magnify — horizontal glass bar bottom-center. Icons magnify on cursor proximity (scale increases closer to cursor). Spring physics on scale changes. Active icon has indicator dot below. Frosted background with border-white/10. Tooltip above on hover.",
            "Floating Pill — pill-shaped glass dock floating bottom-center with margin. 6-8 icon buttons. Hover: icon lifts Y -4px with spring. Active: brand-color dot underneath. Dock itself has subtle shadow-bloom. Icons are Lucide or custom SVG.",
            "Auto-Rail — vertical dock on left edge, hidden off-screen. Mouse approaching left edge triggers slide-in with spring. Icons stacked vertically. Active icon has brand-color background fill. Hover: tooltip pops right. Auto-hides after 2s no hover.",
            "Gaming Bar — horizontal dock with neon border glow (brand color). Icons have individual glow on hover. Notification icons pulse with count badge. Transparent dark background. Icons are slightly larger than typical. Scanline overlay at 3%.",
        ],
    },
    'dropdown': {
        layout: ["Standard select dropdown", "Mega dropdown (multi-column)", "Command palette (search + results)", "Nested sub-menu cascade", "Action menu (right-click context)"],
        surface: ["Frosted glass panel with border-white/10", "Solid dark with subtle shadow", "Outlined with selection highlight", "Glass with gradient active item", "Card-elevated with brand-color accent"],
        motion: ["Scale-in from trigger with spring", "Items stagger-fade from top", "Hover item slides indicator bar", "Selection triggers subtle bounce", "Exit scale-to-zero toward trigger point"],
        mood: ["System menu — compact, keyboard-navigable, clean", "Creative — icons, descriptions, colorful grouped", "Enterprise — categories, badges, breadcrumbs", "Minimal — text only, no icons, tight spacing", "Command — search input, shortcut keys, filtered"],
        composition: ["Navigation sub-menu", "Form select input dropdown", "User menu (avatar trigger)", "Action/context menu (right-click)", "Filter selector dropdown"],
        spawnRecipes: [
            "Glass Command — frosted-glass dropdown with search input at top. Results filter in real-time. Items have icon + label + keyboard shortcut. Active item has brand-color left bar indicator. Scale-in spring from trigger. Keyboard navigable with live highlight.",
            "Cascade Menu — primary menu triggers sub-menus on hover. Sub-menus appear to the right with slide-in animation. Each level has frosted glass. Active trail maintains highlight chain. Clean hierarchy with group labels.",
            "Context Ring — right-click context menu appears with radial animation (items fan out from click point). Glass background. Items grouped with separators. Active item has brand-color fill. Typeahead search support.",
            "Mega Panel — wide dropdown (600px+) with multiple columns. Sections grouped by category with bold headers. Icon + title + description per item. Featured item highlighted with gradient card. Enters via scale-Y from top.",
        ],
    },
    'empty-state': {
        layout: ["Centered icon + text stack", "Illustration + headline + CTA", "Full-page empty state", "Inline empty card", "Split (illustration left, text right)"],
        surface: ["Subtle gradient background with centered content", "Dashed border container (drop zone feel)", "Glass card on dark background", "Outlined container with muted palette", "Full-bleed illustration background"],
        motion: ["Illustration floats with gentle bob animation", "Text fades in staggered after illustration", "CTA button springs in last", "Dashed border animates marching-ants style", "Parallax layers in illustration on mouse move"],
        mood: ["Friendly — cute illustration, warm text, helpful CTA", "Minimal — icon, one line, subtle", "Onboarding — instructional, numbered steps", "Error state — muted, recovery action offered", "Creative — animated character, playful message"],
        composition: ["Table/list with no data yet", "Search with zero results", "Inbox with no messages", "Dashboard new user first visit", "File browser empty folder"],
        spawnRecipes: [
            "Floating Ghost — centered stack with a large (120px) semi-transparent icon that bobs gently (translateY ±8px, 3s loop). Below: headline in muted text, helpful description, and primary CTA button. Button springs in 200ms after text. Clean, calming.",
            "Dashed Drop Zone — dashed border rounded-xl container with marching-ants animation. Centered upload icon + 'Drop files here or click to browse' text. Hover: border turns brand-color solid, background tints. Drag-over: scale 1.02 + glow. Looks interactive.",
            "Onboard Steps — empty state as an onboarding card. 3 numbered steps with icon + instruction. Steps stagger-in on mount. First incomplete step is highlighted. Completion progress indicator at top. CTA: 'Get Started' at bottom.",
            "Illustrated Story — custom SVG illustration (abstract shapes forming a scene). Illustration layers parallax on mouse move. Headline below animation. Brand-color CTA button. Everything fades in with stagger. Premium, not generic.",
        ],
    },
    'feature': {
        layout: ["Bento grid (mixed card sizes)", "Icon + text card grid (3 columns)", "Alternating left-right sections", "Feature carousel horizontal scroll", "List with large icon markers left"],
        surface: ["Glass cards on gradient mesh", "Outlined cards with icon glow", "Solid cards with gradient hover fill", "Full-bleed image sections alternating", "Card with pattern backgrounds (dots, lines)"],
        motion: ["Scroll-triggered stagger entrance by card", "Icon animates/pulses on card hover", "Card tilts 3D on hover", "Feature number counts up on scroll enter", "Background pattern shifts on hover"],
        mood: ["SaaS product — clean, icon-forward, benefit text", "Technical — code snippets, API references, precise", "Creative — illustrations, playful language, color", "Enterprise — conservative, data-backed, professional", "Startup — bold, minimal, high contrast"],
        composition: ["Homepage features section", "Product page capabilities grid", "Landing page benefit blocks", "Documentation feature overview", "Pricing page feature comparison"],
        spawnRecipes: [
            "Glass Bento — mixed-size grid (CSS grid with span-2 hero card). Each card is frosted glass with unique icon. Hero card has gradient background + larger content. Cards stagger-in on scroll. Hover lifts card + adds brand-color glow. Each card has a subtle pattern background (dots/lines/noise) unique from siblings.",
            "Alternating Showcase — full-width sections alternating image-left/text-right, then image-right/text-left. Each section scroll-triggers: image slides in from side, text fades up staggered (badge → headline → description → CTA). Sections separated by subtle gradient dividers.",
            "Icon Grid — 3-column grid of feature cards. Each card: large icon (48px) with brand-color background circle, bold title, description text. Icons animate (spin, bounce, or pulse) on card hover. Cards have subtle border that turns brand-color on hover. Stagger-in on scroll.",
            "Metric Features — feature cards each containing a large animated counter number (e.g., '99.9%', '10M+', '<50ms'). Numbers count-up or type-in on scroll visibility. Below number: feature title and description. Cards separated by thin vertical dividers.",
        ],
    },
    'file-tree': {
        layout: ["Indented tree with toggle arrows", "Flat list with breadcrumb path", "Multi-pane (Miller columns)", "Tree with drag-drop reorder", "Grid + list toggle view"],
        surface: ["Dark with syntax-highlighted file icons", "Outlined with colored indent lines", "Glass panel containing tree", "Minimal – no borders, indent-only hierarchy", "IDE-style with colored file type dots"],
        motion: ["Folder expand with spring height + children stagger", "File hover highlights entire row", "Drag-drop ghost follows cursor", "Folder icon morphs open/closed with SVG animation", "Scroll indicator pulses at edges for overflow"],
        mood: ["IDE — monospace, syntax colors, git status indicators", "File manager — thumbnails, size/date columns, actions", "Documentation — clean, article structure, search", "Minimal — text only, chevron toggles, clean", "Creative — emoji folder icons, playful names"],
        composition: ["Code editor sidebar", "Documentation nav tree", "File upload manager", "Settings/config tree editor", "Component library browser"],
        spawnRecipes: [
            "IDE Explorer — dark panel with monospace file names. Indent guides as vertical dotted lines in brand-color at 20%. Folder arrows rotate with spring on toggle. File icons colored by type (blue: TS, green: SVG, yellow: JSON). Active file has brand-color background highlight. Git status dots (modified: yellow, new: green).",
            "Miller Columns — 3-pane side-by-side navigation. Selecting a folder in column 1 shows contents in column 2. Columns slide in from right with spring. Selected item has brand-color background. Breadcrumb path above columns. Clean, macOS-Finder feel.",
            "Animated Tree — collapsible tree where expanding a folder springs open children with staggered fade-in (50ms delay each). Folder icons morph between open/closed states (SVG animation). Hover highlights entire row with subtle background. Collapse reverses the animation.",
            "Drag Sort Tree — tree with drag-and-drop reordering. Drag ghost is semi-transparent version. Drop targets highlight with dashed border. Items reorder with spring animation. Indent lines shift smoothly during move. Visual connector lines between parents and children.",
        ],
    },
    'file-upload': {
        layout: ["Full drop zone (dashed border area)", "Compact button trigger", "Gallery grid of uploaded files", "Progress list of uploading files", "Combined drop zone + file list"],
        surface: ["Dashed border zone with marching-ants hover", "Glass card with file preview thumbnails", "Outlined list items with progress bars", "Dark zone with neon-glow hover accent", "Minimal with icon + text only"],
        motion: ["Dashed border animates to solid brand-color on drag-over", "File thumbnails spring-scale in on upload complete", "Progress bar fills with gradient animation", "Drop zone pulses on drag-enter", "Upload success: checkmark draws via SVG stroke"],
        mood: ["Functional — clean, clear states, progress-focused", "Creative — image previews, gallery layout, beautiful", "Professional — file type icons, metadata table, strict", "Playful — cloud upload animation, fun illustrations", "Minimal — text link 'click to upload', no chrome"],
        composition: ["Form file input field", "Profile avatar uploader (circular crop)", "Document manager uploader", "Image gallery builder", "Chat message attachment"],
        spawnRecipes: [
            "Neon Drop Zone — large dashed-border area (200px height). Default: muted dashed border, upload cloud icon, instruction text. Drag-over: border turns brand-color solid with glow, background tints, zone scales 1.02. Drop triggers file processing. Uploaded files appear as glass cards in a grid below with thumbnail preview.",
            "Avatar Cropper — circular drop zone with 'click or drag' instruction. After drop: image fills circle with crop handles. Drag to reposition. Scroll to zoom. Confirm button. Processing shows circular progress ring. Complete: avatar image with success checkmark flash.",
            "Progress Stack — compact upload button at top. Uploading files stack below as list items. Each item: file icon, name, size, progress bar with gradient fill, cancel X button. Complete items show green checkmark. Failed items show red X with retry. Items spring-animate in/out.",
            "Gallery Builder — grid of uploaded images as cards. Drop zone is the last grid cell (dashed border). New uploads spring-scale in at drop zone position then flow into grid. Each card: thumbnail, filename, size, delete button (hover reveal). Drag to reorder cards.",
        ],
    },
    'footer': {
        layout: ["Multi-column links grid", "Single-row compact bar", "Mega footer with newsletter + columns", "Stacked centered columns", "Minimal dark bar with credits only"],
        surface: ["Dark gradient from content to void black", "Glass panel separated from main content", "Solid dark with subtle top border", "Gradient mesh background behind columns", "Textured with noise grain overlay"],
        motion: ["Scroll-triggered stagger entrance of columns", "Link hover: underline slides from left", "Newsletter input focus: border glow animation", "Social icons hover: color + lift", "Back-to-top button fade-in at scroll threshold"],
        mood: ["Corporate — structured, legal links, logo heavy", "Startup — minimal, 3-4 links, casual tone", "Creative — animated, illustrated, unique layout", "SaaS — columns: Product, Resources, Company, Legal", "Portfolio — centered, name + social icons only"],
        composition: ["Site-wide global footer", "Landing page bottom section", "Dashboard minimal footer", "Documentation site footer with sitemap", "Marketing page CTA + footer combined"],
        spawnRecipes: [
            "Void Fade — dark gradient footer fading from content bg to #000000 over 200px. Four link columns stagger-in on scroll. Links hover with brand-color + underline slide. Newsletter form with glass input + CTA button. Social icons in a row with hover color + lift. Copyright bar at very bottom in text-xs muted.",
            "Glass Mega — frosted-glass panel with border-top-white/10. Wide layout with 5 columns. Company logo + description in first column, link categories in rest. Bottom bar: copyright + locale selector + theme toggle. Everything staggers in on first scroll-into-view.",
            "Minimal Credits — single dark bar, height 64px. Logo left, copyright text center, social icons right. Social icons hover: scale + brand-color. No link columns. Top border 1px white/5. Clean, minimal, functional.",
            "CTA-Footer Hybrid — upper section: centered CTA block (headline + button + trust badges) on gradient background. Lower section: standard link columns + copyright on dark bg. CTA section animates in powerfully (scale + fade). Clear visual separation between CTA and footer.",
        ],
    },
    'form': {
        layout: ["Single-column vertical stack", "Two-column side-by-side fields", "Multi-step wizard form", "Inline horizontal form (search bar)", "Card-based grouped sections"],
        surface: ["Glass card containing all fields", "Outlined container with section headers", "Flat dark with input focus glow", "Floating labels above inputs", "Paper-style with underline-only inputs"],
        motion: ["Input focus: border glow + label float-up", "Validation shake on error", "Step transition slide left-to-right", "Submit button loading spinner", "Success: form collapses + checkmark reveal"],
        mood: ["Clean modern — floating labels, validation inline", "Conversational — one field at a time, chat-like", "Enterprise — labels, descriptions, grouped sections", "Minimal — underline inputs, lots of space", "Playful — rounded inputs, colorful validation, emoji"],
        composition: ["Sign up / registration form", "Contact/inquiry form", "Settings/preferences form", "Checkout payment form", "Multi-step onboarding wizard"],
        spawnRecipes: [
            "Glass Wizard — multi-step form in a frosted-glass card. Progress bar at top showing step completion. Each step slides in from right (AnimatePresence). Inputs have floating labels that animate up on focus. Validation shows inline with red accent. Final step: submit with loading → success confetti.",
            "Conversational Flow — one field at a time, centered. User types answer, presses Enter, field slides up and next field slides in. Progress dots at bottom. Chat-like feel with assistant text above each field. Keyboard-first. Completion shows summary card.",
            "Dark Dashboard Form — two-column layout on dark background. Inputs have subtle border, brand-color glow on focus. Labels are uppercase text-xs above inputs. Sections grouped with heading + divider. Submit button is full-width at bottom with gradient + magnetic hover.",
            "Inline Validator — single-column form with real-time validation. Valid fields show green checkmark icon. Invalid: red border + shake + error message fades in. Labels float above inputs on focus. Submit disabled until all fields valid. Password strength meter included.",
        ],
    },
};

module.exports = { DNA_3 };
