// ─── Generative DNA Part 7: spinner-loader through video ───
const DNA_7 = {
    'spinner-loader': {
        layout: ["Centered page loader", "Inline button spinner", "Skeleton screen placeholder", "Progress bar (determinate)", "Logo/brand animated loader"],
        surface: ["Circular spinner with brand-color arc", "Dot sequence pulsing", "Skeleton shimmer cards", "Linear progress bar with gradient", "3D rotating brand logo"],
        motion: ["Circular spin with easing (ease-in-out)", "3 dots bounce in sequence", "Skeleton shimmer sweeps left-to-right", "Progress bar fill with animated gradient", "Logo morphs/rotates with spring"],
        mood: ["System — clean spinner, minimal", "Playful — bouncing dots, colorful", "Premium — brand logo animation, smooth", "Technical — progress percentage, ETA", "Immersive — full-page loading experience"],
        composition: ["Page initial load", "Button loading state", "Data fetch placeholder", "Form submission processing", "Content lazy-load skeleton"],
        spawnRecipes: [
            "Arc Spinner — circular ring (32px) with brand-color arc segment. Rotates with spin animation (1s, ease-in-out). Arc length is 75% of circle. Ring has subtle track in muted color. Available in 3 sizes (sm/md/lg). Used inline or centered.",
            "Dot Bounce — 3 circular dots in a row. Each bounces vertically in sequence (200ms stagger). Brand-color fill. Smooth translateY animation with spring. Available in different sizes. Used for 'typing' indicators or loading states.",
            "Shimmer Skeleton — placeholder cards/lines matching content layout shape. Light gray blocks with shimmer gradient sweeping left-to-right continuously. Blocks have rounded corners matching real content. Transitions to real content with crossfade on load.",
            "Brand Pulse — brand logo (or letter mark) pulsing between 0.5 and 1.0 opacity with subtle scale shift (0.95-1.05). Centered on loading page. Below: loading text or progress percentage. Premium, branded loading experience. 2s ease loop.",
        ],
    },
    'table': {
        layout: ["Full data table with headers", "Striped row table", "Card-per-row (mobile-friendly)", "Virtual scrolling table (large data)", "Expandable row table"],
        surface: ["Dark with border-white/5 row dividers", "Alternating row tones", "Glass header, solid body", "Outlined cells grid", "Minimal lines-only (no cell borders)"],
        motion: ["Row hover highlight transition", "Sort: column header click → arrow rotate + data reorder", "Row expand/collapse with spring height", "New row slides in from bottom", "Skeleton rows during data fetch"],
        mood: ["Dashboard — compact, sortable, filterable, action-dense", "Admin — selection checkboxes, bulk actions, editable cells", "Analytics — number-heavy, conditional coloring, sparklines", "Minimal — read-only display, clean lines, simple", "Financial — fixed columns, decimal alignment, alternating rows"],
        composition: ["Data management dashboard", "Admin panel listings", "Analytics report table", "Settings configuration table", "Search results listing"],
        spawnRecipes: [
            "Glass Dashboard Table — dark table with frosted-glass sticky header. Cell borders in white/5. Row hover: row background highlights. Sortable columns: click header → sort indicator rotates, data animates reorder. Pagination below. Checkbox column for selection. Actions column with icon buttons.",
            "Expandable Rows — each row can expand to show detail panel below. Expand trigger: chevron rotates with spring. Detail area springs open height + content fades up. Multiple rows can be expanded. Clean hierarchy. Used for order details, user profiles, etc.",
            "Card Table — on mobile, each row transforms into a card with key-value pairs stacked vertically. Responsive breakpoint switches between table (desktop) and card (mobile) layouts. Cards stagger-in on mobile scroll. Clean responsive pattern.",
            "Virtual Scroll — table handles 100K+ rows with row virtualization. Only visible rows rendered. Smooth 60fps scrolling at any speed. Skeleton rows at edges of viewport. Sticky header. Fixed first column. Resizable column widths. Real enterprise performance.",
        ],
    },
    'tab': {
        layout: ["Horizontal tab bar with content panel", "Vertical tab list sidebar", "Pill/segmented control tabs", "Underline tab bar", "Scrollable tab strip (overflow)"],
        surface: ["Glass tab bar with active indicator", "Outlined tabs with active fill", "Underline indicator bar (brand-color)", "Pill-shaped active background", "Card-style raised active tab"],
        motion: ["Active indicator slides between tabs (layoutId spring)", "Content panel crossfades on tab change", "Tab hover: subtle background fill", "Active tab icon animates/bounces", "Content enters from direction of tab (left→right or right→left)"],
        mood: ["Dashboard — compact, icon+label, badge counts", "Settings — section selector, full-width panels", "Documentation — clean, content-focused, code tabs", "Creative — large tabs, animated transitions, playful", "Minimal — text-only, underline indicator, spare"],
        composition: ["Settings page section switcher", "Dashboard multi-view tabs", "Code block language tabs", "Product detail tabs (Description/Reviews/Specs)", "Profile page section tabs"],
        spawnRecipes: [
            "Sliding Pill — horizontal tabs with active tab background as a pill shape that slides between tabs using layoutId animation (spring physics). Inactive tabs: transparent. Active: brand-color fill with white text. Content crossfades below. Clean, app-like.",
            "Underline Glide — horizontal text tabs with a 2px bottom border indicator that slides between active tabs (spring animation). Text brightens on active. Content transitions based on direction (tab index delta determines slide left/right). Clean, editorial.",
            "Vertical Section — vertical tab list on left (200px), content panel on right. Active tab has brand-color left bar + background fill. Tabs are full-width buttons with icon + label. Content crossfades on change. Responsive: collapses to dropdown trigger on mobile.",
            "Icon Tabs — tabs with icon above label. Active icon fills/animates (brand color). Badge count on tab icon for notifications. Tab bar has subtle bottom border. Content panel scrollable. Active indicator dot below tab. Used for app section. tabs.",
        ],
    },
    'tag': {
        layout: ["Inline pill tag", "Tag list with wrapping", "Removable tag with X", "Tag input field (type to create)", "Grouped tags by category"],
        surface: ["Solid brand-color fill with dark text", "Outlined with brand-color border", "Gradient fill tag", "Glass tag with backdrop blur", "Muted background with colored dot prefix"],
        motion: ["Tag created: spring-scale in from zero", "Tag removed: collapse width + fade", "Hover: lift with shadow increase", "Tag input: new tag pops in on Enter", "Drag to reorder tags"],
        mood: ["Content — blog categories, subtle, muted", "Status — colored by state (active/archived/draft)", "Technical — code-like, monospace, compact", "Social — hashtags, clickable, interactive", "Design — color swatches, visual, brand-heavy"],
        composition: ["Blog post categories", "Filter/facet selected values", "Skill/technology labels", "Product feature tags", "Search tag refinement"],
        spawnRecipes: [
            "Glass Pill — frosted-glass tag with backdrop-blur-sm. Brand-color text. Rounded-full. Hover: lift + shadow. Removable variant has X button that fades in on hover. Created with spring-scale animation. Removed with width-collapse. Used for filters, categories.",
            "Status Tag — small rounded pill with colored dot prefix (green: active, yellow: pending, red: error). Background matches dot color at 10% opacity. No border. Text in standard weight. Compact (24px height). Used in tables, lists for status indication.",
            "Input Tags — text input that creates tags on Enter key. Tags appear as pills inside the input area. Each new tag pops in with spring-scale. Remove via X button or Backspace key. Tags wrap to multiple lines. Used for multi-value inputs (skills, emails, categories).",
            "Category Cloud — collection of tags in varying sizes based on frequency/importance. Larger tags are more prominent. Tags arranged in a cloud layout (flex wrap). Hover: tag lifts + brand-color underline. Clickable for filtering. Stagger-in on scroll.",
        ],
    },
    'testimonial': {
        layout: ["Card grid (2-3 columns)", "Single testimonial spotlight", "Carousel slider", "Masonry wall", "Quote + avatar inline strip"],
        surface: ["Glass cards on gradient background", "Solid dark cards with quote marks", "Outlined cards with avatar header", "Full-bleed image background with overlay", "Clean white cards with shadow"],
        motion: ["Cards stagger-in on scroll", "Carousel auto-rotates with crossfade", "Quote marks float in before text", "Avatar pops in with spring", "Star rating fills in sequentially"],
        mood: ["Premium — dark, large quote, subtle, one at a time", "Social proof — many small cards, volume over size", "Personal — large avatar, name/role, detailed quote", "Enterprise — company logos, role titles, formal", "Creative — photo backgrounds, overlay text, editorial"],
        composition: ["Homepage social proof section", "Product page reviews", "Landing page trust block", "Case study page header", "About page team testimonials"],
        spawnRecipes: [
            "Glass Wall — 3-column masonry grid of glass testimonial cards. Each: large open-quote glyph (brand-color, 48px), quote text, avatar + name + role footer. Cards stagger-in on scroll viewport enter. Hover: card lifts with shadow bloom. Star rating below quote. Varied card heights create masonry effect.",
            "Spotlight Rotator — single large testimonial, centered. Auto-rotates every 6s with crossfade transition. Large avatar (64px), name, role, company logo. Quote in text-xl italic. Navigation dots below. Pause on hover. Brand-color accent line above quote. Premium, focused.",
            "Logo Strip — horizontal scrolling strip of company logos. Below each logo: one short testimonial sentence. Infinite ticker scroll. Hover pauses and shows full testimonial in popover above. Clean, volume-focused social proof.",
            "Video Testimonials — grid of cards where each contains a video thumbnail with play button overlay. Click: modal opens with video player. Name + role below video. Play button has brand-color glow. Cards stagger-in. Engaging, high-trust format.",
        ],
    },
    'text': {
        layout: ["Heading hierarchy (h1-h6)", "Paragraph body text", "Animated text reveal", "Code/monospace text block", "Gradient text display"],
        surface: ["Gradient fill text (CSS background-clip)", "Solid brand-color headings", "Matte body text with line-height 1.6", "Text with subtle text-shadow glow", "Outlined/stroke text (no fill)"],
        motion: ["Typewriter character-by-character reveal", "Word-by-word fade-up stagger", "Letter-by-letter spring entrance", "Text blur-in from 20px to 0", "Gradient hue-shift animation on text"],
        mood: ["Editorial — serif, elegant, sophisticated spacing", "Technical — monospace, precise, code-like", "Bold branding — oversized, gradient, all-caps", "Minimal — thin weight, generous spacing, quiet", "Playful — variable sizes, colorful, animated"],
        composition: ["Hero headline", "Section titles", "Body copy paragraphs", "Code snippets inline", "Brand statement"],
        spawnRecipes: [
            "Gradient Headline — large heading (text-5xl to text-7xl) with CSS gradient text (background-clip: text). Gradient shifts through brand spectrum. Optional: gradient animates slowly (translate background-position). Bold weight. Used for hero headlines and section titles.",
            "Stagger Words — sentence where each word fades up individually with stagger delay (80ms per word). Uses Framer Motion with variants. Words start at opacity:0 y:20px and animate to opacity:1 y:0. Scroll-triggered or on mount. Impactful for important headlines.",
            "Typewriter — text reveals character by character with a blinking cursor at the end. Cursor blinks at 500ms interval. Text appears at configurable speed. Optional: multiple strings that type, pause, delete, and type next (TypeIt style). Monospace or sans-serif.",
            "Blur Reveal — text starts with blur(12px) and opacity:0. On scroll/mount, transitions to blur(0) and opacity:1 over 800ms with ease-out. Entire block reveals together. Subtle, premium effect. Can be combined with y-translate for drift-in.",
        ],
    },
    'text-area': {
        layout: ["Standard multi-line textarea", "Auto-expanding textarea", "Textarea with character count", "Textarea with toolbar (rich text)", "Code editor textarea"],
        surface: ["Dark with glow border on focus", "Outlined with resize handle", "Glass with backdrop blur", "Underline-only (minimal style)", "Solid fill with no visible border"],
        motion: ["Focus: border glow transitions to brand-color", "Auto-resize: height animates smoothly", "Character count: color shifts as limit approaches", "Toolbar: items stagger-in on focus", "Error: border turns red + shake animation"],
        mood: ["Chat — auto-resize, send button, attachment option", "Form — label, placeholder, character limit, validation", "Code — monospace, line numbers, syntax potential", "Note — large, minimal, distraction-free", "Feedback — star rating above textarea, submit below"],
        composition: ["Contact form message field", "Chat message composer", "Comment/reply box", "Code/markdown editor", "Notes/journal entry field"],
        spawnRecipes: [
            "Auto-Grow Glass — frosted-glass textarea that auto-expands height as user types. Smooth height transition (spring). Focus: brand-color border glow. Character count in bottom-right corner, turns orange at 80% and red at 100%. Placeholder fades out on type.",
            "Chat Composer — compact textarea (2 lines default) with send button to right. Auto-grows up to 6 lines. Attachment button left. Shift+Enter for new line, Enter to send. Focus glow. Button pulses when message is ready. Used in chat interfaces.",
            "Code Input — monospace textarea with dark (#0d0d0d) background. Line numbers on left. Tab key inserts spaces (not focus change). Focus: subtle green border. Resize handle. Scrollbar thin and styled. Used for code/JSON input fields.",
            "Toolbar Rich — textarea with formatting toolbar above (Bold, Italic, Link, List icons). Toolbar items have hover highlight. Toolbar fades/slides in on focus, out on blur. Textarea below with clean styling. Word count in footer bar. Form-field usage.",
        ],
    },
    'toast': {
        layout: ["Top-right stacked toasts", "Bottom-center single toast", "Full-width top banner toast", "Floating pill toast (centered)", "Bottom-right with undo action"],
        surface: ["Glass with colored left accent bar", "Solid dark card with icon circle", "Gradient-accented by severity", "Minimal text-only toast", "Rich toast with image/avatar preview"],
        motion: ["Slide in from right with spring", "Rise from bottom with fade", "Auto-dismiss: progress bar drains", "Dismiss: swipe gesture or collapse", "Stack reorders with layout animation"],
        mood: ["System — clean, severity-colored, auto-dismiss", "Social — avatar, action description, interactive", "Undo — action confirmation with undo link/timer", "Minimal — text only, short, unobtrusive", "Rich — preview image, CTA button, persistent"],
        composition: ["Form submission feedback", "Background action confirmation", "Error/warning notification", "Undo action prompt", "System status update"],
        spawnRecipes: [
            "Sonner Glass — stacked glass toasts in bottom-right (or via Sonner library). Each: severity icon + title + description. Slide up from bottom with spring. Stack with 8px gaps. Auto-dismiss with progress bar (brand-color draining left-to-right). Swipe right to dismiss. Newest on bottom.",
            "Undo Bar — centered bottom bar (pill-shaped) with action description + 'Undo' button + countdown timer. Appears with rise + fade. Auto-dismisses after countdown (5s). Undo click cancels action and collapses bar. Clean, non-blocking, useful.",
            "Rich Preview — toast card with small image/avatar preview, text summary, and action button. Slides in from right. Persistent until dismissed. Used for notifications, messages, social actions. Glass surface. Close X in corner.",
            "Minimal Pill — small rounded-full pill at top-center. Single line of text. Success: green accent. Error: red. Slides down from top. Auto-fades after 3s. No interaction needed. Smallest possible footprint. Unobtrusive status feedback.",
        ],
    },
    'toggle': {
        layout: ["Standard horizontal toggle switch", "Toggle with label on both sides (On/Off)", "Icon toggle (sun/moon theme switch)", "Toggle group (multiple toggles in section)", "Large toggle card (feature toggle)"],
        surface: ["Pill track with circular thumb", "iOS-style green/gray toggle", "Dark track with glowing thumb", "Outlined track with solid thumb", "Glass track with brand-color active fill"],
        motion: ["Thumb slides with spring physics", "Track color transitions smoothly", "Thumb size pulse on state change", "Icon morph (sun ↔ moon) during toggle", "Ripple expands from thumb on change"],
        mood: ["System — iOS/Android standard toggle feel", "Settings — label + description + toggle row", "Theme — light/dark mode switch, icon morphing", "Premium — glass, glow effects, tactile feel", "Gaming — neon, pulse effects, dramatic state change"],
        composition: ["Settings preference toggle", "Theme mode switcher", "Feature enable/disable", "Form boolean input", "Dashboard widget visibility toggle"],
        spawnRecipes: [
            "Spring Switch — pill-shaped track (48x24px). Circular thumb slides between left and right with spring physics (stiffness: 500, damping: 30). Off: gray track. On: brand-color track with glow. Thumb size pulses slightly on change (scale 1.1 → 1.0). Satisfying spring overshoot.",
            "Theme Morph — toggle switch where thumb contains an icon that morphs between sun (☀) and moon (🌙) using SVG path interpolation. Track color transitions. Sun rays rotate in. Moon craters fade in. Used for light/dark mode. Premium, delightful micro-interaction.",
            "Cinematic Glow — dark track with lit thumb. On state: thumb glows brand-color with box-shadow bloom. Track brightens. Off: thumb is matte gray, track is dark. Transition is smooth 300ms. Hover: subtle glow even in off state. Premium, cinematic feel.",
            "Feature Card Toggle — full-width card with feature icon, title, description on left. Toggle switch on right. Card has subtle border. Toggle on: card gets faint brand-color background tint. Used in settings pages for feature flags. Clean, scannable layout.",
        ],
    },
    'tooltip': {
        layout: ["Floating above trigger", "Floating below trigger", "Side-anchored (left/right)", "Multi-line content tooltip", "Rich tooltip with card-style content"],
        surface: ["Frosted glass with border-white/10", "Solid dark with arrow pointer", "Brand-color background with white text", "Glass with gradient accent border", "Outlined card with subtle shadow"],
        motion: ["Pop in with scale spring from anchor", "Fade in with 200ms delay", "Slide in from anchor direction (top/bottom/left/right)", "Content staggers in (icon → label → description)", "Exit: scale to zero toward anchor point"],
        mood: ["System — small text tip, clean, functional", "Rich preview — larger card with metadata/image", "Keyboard shortcut — small pill, shortcut key label", "Contextual help — icon + description, learn-more link", "Status — colored by state, minimal text"],
        composition: ["Icon button hover label", "Truncated text full reveal", "Keyboard shortcut hint", "Form field help text", "Navigation item description"],
        spawnRecipes: [
            "Glass Whisper — small frosted-glass tooltip with backdrop-blur-md. Appears on hover after 200ms delay. Positioned dynamically to stay in viewport. Arrow pointer in matching glass style. Text in text-xs. Spring-scale entrance from anchor. Exit with quick fade. Border-white/10.",
            "Rich Preview — larger tooltip card appearing on hover. Contains: icon, title, description, optional action link. Glass surface. Content staggers in (icon first, text follows). Used for complex hover previews. Keyboard accessible (focus-triggered). Max-width 280px.",
            "Shortcut Pill — tiny pill-shaped tooltip (rounded-full, ~24px height) showing keyboard shortcut (e.g., '⌘K'). Monospace text. Muted background. Appears instantly on hover. Used next to menu items and action buttons. Minimal, functional.",
            "Status Tip — tooltip with colored dot indicator (green/yellow/red) + status text. Dot pulses for active states. Used on avatar status dots, system indicators. Glass surface. Arrow pointer. Quick fade-in entrance. Small, informative.",
        ],
    },
    'video': {
        layout: ["Full-width hero video player", "Card-embedded video", "Video grid gallery", "Background ambient video loop", "Inline video with transcript"],
        surface: ["Dark player with custom controls", "Glass container for video card", "Borderless full-bleed video", "Rounded card with poster image", "Outlined frame with title bar"],
        motion: ["Play button pulse on hover", "Video fades in on load", "Custom controls fade in/out on hover", "Progress bar with seek preview", "Poster to video crossfade on play"],
        mood: ["Cinematic — full-screen, custom controls, dark UI", "Product — demo video, clean player, branded", "Social — autoplay, muted, inline, compact", "Educational — chapters, transcript, playback speed", "Background — ambient loop, no controls, atmospheric"],
        composition: ["Hero section background", "Product demo showcase", "Testimonial video section", "Tutorial/course video player", "Background ambient texture"],
        spawnRecipes: [
            "Cinematic Player — dark custom player with rounded-2xl container. Custom control bar: play/pause, progress bar with hover preview, volume, fullscreen. Controls fade in on hover, hide after 2s. Progress bar shows buffer + played. Brand-color accent. Poster image with large centered play button.",
            "Ambient Loop — full-width video background, muted, autoplay, loop. No visible controls. Dark gradient overlay for text readability. Video loads with blur-to-sharp transition. Poster image as fallback. Pointer-events-none (click-through). Sets mood without demanding attention.",
            "Card Video — video embedded in glass card. Poster image with play button overlay. Click: poster fades, video plays. Title and description below video. Like/share actions footer. Card hover lifts. Used in video galleries. Responsive aspect ratio maintained.",
            "Gallery Grid — responsive grid of video thumbnail cards. Each: poster image, play icon overlay, title, duration badge. Click opens modal/lightbox player (full-size). Thumbnails stagger-in on scroll. Hover: slight zoom on poster. Duration badge top-right corner.",
        ],
    },
};

module.exports = { DNA_7 };
